# Generated by Django 5.1.6 on 2025-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_remove_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkup_done',
            field=models.BooleanField(default=False),
        ),
    ]
