# Generated by Django 5.1.6 on 2025-02-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0006_healtharticle_labtest_medicineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='checkup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
