# Generated by Django 5.1.6 on 2025-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0008_medicine_medicineorder_status_medicineorder_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_lab_tester',
            field=models.BooleanField(default=False),
        ),
    ]
