# Generated by Django 5.1.6 on 2025-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_doctorprofile_is_lab_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_lab_test',
            field=models.BooleanField(default=False),
        ),
    ]
