# Generated by Django 5.1.6 on 2025-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0011_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
